# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import template_pb2 as template__pb2


class TemplateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.apiEndpoint1 = channel.unary_unary(
                '/Template/apiEndpoint1',
                request_serializer=template__pb2.inputObj.SerializeToString,
                response_deserializer=template__pb2.resultObj.FromString,
                )


class TemplateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def apiEndpoint1(self, request, context):
        """Simple call (Http GET-like)
        Change function name
        Change input class name
        Change return class name
        Add more if necessary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemplateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'apiEndpoint1': grpc.unary_unary_rpc_method_handler(
                    servicer.apiEndpoint1,
                    request_deserializer=template__pb2.inputObj.FromString,
                    response_serializer=template__pb2.resultObj.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Template', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Template(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def apiEndpoint1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Template/apiEndpoint1',
            template__pb2.inputObj.SerializeToString,
            template__pb2.resultObj.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
