# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import system_pb2 as system__pb2


class SystemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.doList = channel.unary_unary(
                '/System/doList',
                request_serializer=system__pb2.item.SerializeToString,
                response_deserializer=system__pb2.result.FromString,
                )
        self.doBid = channel.unary_unary(
                '/System/doBid',
                request_serializer=system__pb2.bid.SerializeToString,
                response_deserializer=system__pb2.result.FromString,
                )
        self.doQuery = channel.unary_unary(
                '/System/doQuery',
                request_serializer=system__pb2.item.SerializeToString,
                response_deserializer=system__pb2.result.FromString,
                )


class SystemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def doList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'doList': grpc.unary_unary_rpc_method_handler(
                    servicer.doList,
                    request_deserializer=system__pb2.item.FromString,
                    response_serializer=system__pb2.result.SerializeToString,
            ),
            'doBid': grpc.unary_unary_rpc_method_handler(
                    servicer.doBid,
                    request_deserializer=system__pb2.bid.FromString,
                    response_serializer=system__pb2.result.SerializeToString,
            ),
            'doQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.doQuery,
                    request_deserializer=system__pb2.item.FromString,
                    response_serializer=system__pb2.result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'System', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class System(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def doList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/System/doList',
            system__pb2.item.SerializeToString,
            system__pb2.result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def doBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/System/doBid',
            system__pb2.bid.SerializeToString,
            system__pb2.result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def doQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/System/doQuery',
            system__pb2.item.SerializeToString,
            system__pb2.result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
